### ISSUE TITLE
[Feature Request] Zutaten Reihenfolge

### ISSUE THREAD

**Issue by Tuxrocks** [AndreWohnsland/CocktailBerry#119]
Hallo André 
Was ich mir noch wünschen würde wäre die Möglichkeit für die Zutaten eine Reihenfolge festlegen zu können.
Manche Cocktails haben ja eine Schichtung ,es kommt eine Zutat zum Schluss oder am Anfang ins Glas.
Meine Idee wäre im Rezept einfach eine Zahl vor die Zutat zu setzen um die Reihenfolge festzulegen.
z.B:
1  — Zutat 1
1  — Zutat 2
1  — Zutat 3
2 — Zutat 4
Somit würde Zutat 1,2 und 3 gleichzeitig gepumpt und Zutat 4 als letztes.
Gerne würde ich das selbst realisieren aber da ich eher ein Laie beim Programmieren bin würde das wohl ewig dauern. 
Schon im Vorraus danke für deine Mühen!
Mit freundlichen Grüßen 
Ralf

**Comment by AndreWohnsland** [comment]
Hi,

Ich bin derzeit noch an nem anderen großen Feature. Wenn ich damit durch bin, schaue ich mir eine Umsetzbarkeit mal genauer an. Ich sehe an der einen oder anderen Stelle im Code / UI Herausforderungen bei der Implementation, hab jedoch auch ein paar Lösungsansätze dafür. Grundsätzlich sehe ich das Feature aber als machbar. Ich halte dich hier in issue auf dem Laufenden wenn ich soweit bin mir das mal anzuschauen.

LG
