### ISSUE TITLE
RPi 5 does not work due to GPIO changes

### ISSUE THREAD

**Issue by felpi13** [AndreWohnsland/CocktailBerry#169]
After Installation of Cocktailberry on a brandnew Raspberry 5 I get the following message:

RuntimeError: The GPIO channel has not been set up as an OUTPUT
Press Enter to close

What can i do and how can I fix this Problem?
Can't read anything on the Web Page.

Best regards,

**Comment by AndreWohnsland** [comment]
Hi, can you provide for more information the logfiles in `~/CocktailBerry/logs/` and the config from `~/CocktailBerry/custom_config.yaml` so I can see what exactly is going on? 
Is it a clean installation, without any changes and did you use the installer script where you run just one command?

**Comment by AndreWohnsland** [comment]
Hi, is this still an issue?

**Comment by felpi13** [comment]
Hi,
thanks for your answer. I have solved the Problem by using a Raspi 3b+.
With a Raspi 5 I found no way to get the software running.

Best regards,
Felix
________________________________
Von: Andre Wohnsland ***@***.***>
Gesendet: Sonntag, 8. September 2024 09:57
An: AndreWohnsland/CocktailBerry ***@***.***>
Cc: felpi13 ***@***.***>; Author ***@***.***>
Betreff: Re: [AndreWohnsland/CocktailBerry] Runtime error after installation (Issue #169)


Hi, is this still an issue?

**Comment by AndreWohnsland** [comment]
Thanks for the feedback. I haven’t tested personally on a pi 5, I think most users are on a pi 4 (pi 5 is quite the overkill). When I get my hands on a pi5 I will test (and potentially fix) the software for the pi5.

**Comment by AndreWohnsland** [comment]
As an update, the error originates from `RuntimeError: Cannot determine SOC peripheral base address` -> this is due to the new RPi 5 GPIO mapping, which now is different from the 3/4. But I think with some changes in the code, this will soon also work for the RPi 5 :)
