### ISSUE TITLE
No module named typing

### ISSUE THREAD

**Issue by ChrisOle14** [AndreWohnsland/CocktailBerry#70]
Guten Abend. Ich habe eben deinen Beitrag zum Cocktailberry gelesen und wollte es mal auf meiner Cocktailmaschine ausprobieren. Habe deinen all in one code benutzt klappte soweit so gut. Allerdings beim start kommt die Fehlermeldung : Import Error: No module named typing .

Da ich mit Programmieren nicht besonders geschickt bin hoffe ich auf deine Hilfe .

Mit freundlichen grüßen und Dank im voraus Christian

**Comment by AndreWohnsland** [comment]
This issue can usually be resolved by using the recommended Python version (3.9 or later). 
The typing module ships by default with Python 3.5 or newer.
Typing `python -V` will show if this requirement is met.

If this error still persists, 
```
sudo apt --fix-broken install
# or
pip install typing
``` 

should fix this issue.
